export const CHANNEL_GRID_BATCH = 96;
export const FIXTURES_POLL_INTERVAL_MS = 90_000;
export const HIDE_CONTROLS_AFTER_MS = 3500;
export const HIDE_CONTROLS_INITIAL_MS = 8000;
export const LINK_RETRY_DELAY_MS = 800;
export const HLS_FRAG_LOAD_TIMEOUT_MS = 9_000;
export const RECENTLY_WATCHED_MAX = 10;
export const FAVORITES_MAX = 30;
